### ISSUE TITLE
data问题

### ISSUE THREAD

**Issue by gaoyinglei** [xrb92/IKRL#1]
您好，data中缺少image2vec_fc7.txt文件，也没有图片，我根据wnid和imageid去网上爬的时候很多图片链接都失效了，请问您可以给我image2vec_fc7.txt或者是图片吗？

**Comment by haipeng123** [comment]
> 您好，data中缺少image2vec_fc7.txt文件，也没有图片，我根据wnid和imageid去网上爬的时候很多图片链接都失效了，请问您可以给我image2vec_fc7.txt或者是图片吗？
您好，请问您找到这个文件了吗？可以发给我吗，我的邮箱是1679354383@qq.com
